-- Jockey de galop 
INSERT INTO Jockey (jockeyid, nom, prenom, nationalite, poids, discipline, gain)
VALUES (1, 'Barzalona', 'Mickaël', 'Francais', 56, 'Galop', 0),
       (2, 'Guyon', 'Maxime', 'Francais', 57, 'Galop', 0),
       (3, 'Pouchin', 'Alexis', 'Francais', 58, 'Galop', 0),
       (4, 'Soumillon', 'Christophe', 'Belge', 55, 'Galop', 0),
       (5, 'Lefebvre', 'Clément', 'Francais', 53, 'Galop', 0),
       (6, 'Bachelot', 'Théo', 'Francais', 52, 'Galop', 0),
       (7, 'Pasquier', 'Stéphane', 'Francais', 59.5, 'Galop', 0),
       (8, 'Vélon', 'Marie', 'Francais', 51, 'Galop', 0),
       (9, 'Piccone', 'Tony', 'Francais', 55, 'Galop', 0),
       (10, 'Wayne', 'Jordan', 'Irlandais', 60.5, 'Galop', 0),
       (11, 'Keane', 'Colin', 'Irlandais', 58, 'Galop', 0),
       (12, 'Atzeni', 'Andrea', 'Italien', 60.5, 'Galop', 0),
       (13, 'McMonagle', 'Dylan', 'Irlandais', 59, 'Galop', 0),
       (14, 'Mendizabal', 'Ioritz', 'Espagnol', 58, 'Galop', 0),
       (15, 'Kitamura', 'Yuichi', 'Japonais', 57, 'Galop', 0),
       (16, 'Murphy', 'Oisin', 'Irlandais', 56.5, 'Galop', 0),
       (17, 'Demuro', 'Cristian', 'Italien', 54, 'Galop', 0),
       (18, 'Buick', 'William', 'Anglais', 61.5, 'Galop', 0),
       (19, 'Foley', 'Shane', 'Australien', 57, 'Galop', 0),
       (20, 'Lemaire', 'Christophe', 'Francais', 56, 'Galop', 0),
       (21, 'Marquand', 'Tom', 'Anglais', 60, 'Galop', 0),
       (22, 'Doyle', 'Hollie', 'Anglai', 51.5, 'Galop', 0),
       (23, 'Orani', 'Antonio', 'Francais', 54, 'Galop', 0),
       (24, 'Madamet', 'Augustin', 'Francais', 53, 'Galop', 0),
       (25, 'Michel', 'Mickaëlle', 'Francais', 50, 'Galop', 0),
       (26, 'Thomas', 'Ronan', 'Francais', 58, 'Galop', 0),
       (27, 'Journiac', 'Hugo', 'Francais', 55, 'Galop', 0),
       (28, 'Roussel', 'Alexandre', 'Francais', 56, 'Galop', 0),
       (29, 'Molins', 'Ambre', 'Francais', 49, 'Galop', 0),
       (30, 'Pacaut', 'Coralie', 'Francais', 50, 'Galop', 0),
       (31, 'Eon', 'Marie', 'Francais', 51, 'Galop', 0),
       (32, 'Chevillard', 'Théo', 'Francais', 54, 'Galop', 0),
       (33, 'Tosaki', 'Kaito', 'Japonais', 55, 'Galop', 0),
       (34, 'Moreira', 'Joao', 'Brésilien', 52, 'Galop', 0),
       (35, 'Crastus', 'Anthony', 'Francais', 56, 'Galop', 0),
       (36, 'Martin', 'Sophie', 'Francais', 52, 'Galop', 0),
       (37, 'Lane', 'Damien', 'Australien', 59, 'Galop', 0),
       (38, 'Lopez', 'Carlos', 'Espagnol', 57, 'Galop', 0),
       (39, 'Gonzalez', 'Santiago', 'Espagnol', 60, 'Galop', 0),
       (40, 'Moore', 'Ryan', 'Anglais', 59.5, 'Galop', 0);

-- Jockey de trot
INSERT INTO Jockey (jockeyid, nom, prenom, nationalite, poids, discipline, gain)
VALUES
(41, 'Raffin', 'Eric', 'Francais', 62, 'Trot', 0),
(42, 'Bazire', 'Jean-Michel', 'Francais', 66, 'Trot', 0),
(43, 'Abrivard', 'Matthieu', 'Francais', 61, 'Trot', 0),
(44, 'Abrivard', 'Alexandre', 'Francais', 59, 'Trot', 0),
(45, 'Thomain', 'David', 'Francais', 63, 'Trot', 0),
(46, 'Rochard', 'Benjamin', 'Francais', 62, 'Trot', 0),
(47, 'Lebourgeois', 'Yoann', 'Francais', 61, 'Trot', 0),
(48, 'Nivard', 'Franck', 'Francais', 62, 'Trot', 0),
(49, 'Barrier', 'Anthony', 'Francais', 64, 'Trot', 0),
(50, 'Gelormini', 'Gabriele', 'Italien', 60, 'Trot', 0),
(51, 'Monclin', 'Jean-Philippe', 'Francais', 61, 'Trot', 0),
(52, 'LeBeller', 'Tony', 'Francais', 63, 'Trot', 0),
(53, 'Derieux', 'Romain', 'Francais', 62, 'Trot', 0),
(54, 'Vercruysse', 'Pierre', 'Francais', 64, 'Trot', 0),
(55, 'Ensch', 'Nicolas', 'Francais', 65, 'Trot', 0),
(56, 'Guelpa', 'Junior', 'Francais', 62, 'Trot', 0),
(57, 'Daugeard', 'Philippe', 'Francais', 63, 'Trot', 0),
(58, 'Ouvrie', 'Franck', 'Francais', 61, 'Trot', 0),
(59, 'Mottier', 'Mathieu', 'Francais', 59, 'Trot', 0),
(60, 'Ploquin', 'Paul-Philippe', 'Francais', 58, 'Trot', 0),
(61, 'Duvaldestin', 'Théo', 'Francais', 57, 'Trot', 0),
(62, 'Duvaldestin', 'Clément', 'Francais', 56, 'Trot', 0),
(63, 'Bekaert', 'David', 'Francais', 62, 'Trot', 0),
(64, 'Roubaud', 'Jean-Marie', 'Francais', 64, 'Trot', 0),
(65, 'Verva', 'Pierre-Yves', 'Francais', 63, 'Trot', 0),
(66, 'Callier', 'Pierre', 'Francais', 64, 'Trot', 0),
(67, 'Lamy', 'Etienne', 'Francais', 59, 'Trot', 0),
(68, 'Souloy', 'Fabrice', 'Francais', 65, 'Trot', 0),
(69, 'Bigeon', 'Christian', 'Francais', 63, 'Trot', 0),
(70, 'Wiels', 'Antoine', 'Francais', 62, 'Trot', 0),
(71, 'LeBeller', 'Bertrand', 'Francais', 61, 'Trot', 0),
(72, 'Monthule', 'Hugues', 'Francais', 61, 'Trot', 0),
(73, 'Martin', 'Guillaume', 'Francais', 59, 'Trot', 0),
(74, 'Gocciadoro', 'Alessandro', 'Italien', 62, 'Trot', 0),
(75, 'Goop', 'Bjorn', 'Suedois', 61, 'Trot', 0),
(76, 'Verbeeck', 'Jos', 'Belge', 64, 'Trot', 0),
(77, 'Tiepolo', 'Luca', 'Italien', 63, 'Trot', 0),
(78, 'Berg', 'Erik', 'Suedois', 62, 'Trot', 0),
(79, 'Silva', 'Carlos', 'Portugais', 60, 'Trot', 0),
(80, 'Johansson', 'Oskar', 'Suedois', 61, 'Trot', 0);


-- Cheval de galop
INSERT INTO Cheval (chevalid, nom, datenaiss, race, age, sexe, poids, discipline, gain)
VALUES